// marvin-vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import Marvin from './views/Marvin.vue'
import Examples from './views/examples/Examples.vue'
import type { Marvin as MarvinRef } from '@chemaxon/marvin'

const marvinRef = ref<MarvinRef | null>(null)

const setMarvinRef = (refValue: MarvinRef) => {
  marvinRef.value = refValue
}
</script>

<template>
  <section id="app">
    <Marvin :settings="{}" @update-marvin-ref="setMarvinRef" />
    <Examples :marvinRef="marvinRef" />
  </section>
</template>

<style>
#app {
  display: flex;
  flex-direction: row;
  width: 100vw;
  flex: 1;
}

* {
  box-sizing: border-box;
}
</style>

// marvin-react/src/App.tsx
import { useState } from "react";
import "./App.css";
import Examples from "./components/examples/Examples";
import Marvin from "./components/marvin/Marvin";
import { Marvin as MarvinRef } from "@chemaxon/marvin";

function App() {
  const [marvinRef, setMarvinRef] = useState<MarvinRef>();
  return (
    <section id="app">
      <Marvin settings={{}} setMarvinRef={setMarvinRef} />
      <Examples marvinRef={marvinRef} />
    </section>
  );
}

export default App;
