// marvin-svelte/src/lib/components/marvin/Marvin.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Marvin as MarvinRef } from '@chemaxon/marvin';

  export let settings: any;
  export let setMarvinRef: (ref: MarvinRef) => void;

  onMount(async () => {
    // Set the host for Marvin Web Services for custom / separate backend
    // Example: const MARVIN_WEBSERVICES_HOST = "http://localhost:8080/";
    const MARVIN_WEBSERVICES_HOST = "";
    
    const marvinContainer = document.getElementById('marvin-app');
    const marvin = await import('@chemaxon/marvin');
    const marvinSettings = await import('@chemaxon/marvin/marvin-extensions');
    const createMarvin = marvin.createMarvin;
    const getDefaultSettings = marvinSettings.getDefaultSettings;

    if (marvinContainer) {
      createMarvin(marvinContainer, {
        ...getDefaultSettings(MARVIN_WEBSERVICES_HOST),
        ...settings
      }).then((marvin: MarvinRef) => {
        setMarvinRef(marvin);
      });
    }
  });
</script>

<div id="marvin-app"></div>

<style>
  #marvin-app {
    width: 70%;
  }
</style>

// marvin-angular/src/app/marvin/marvin.component.ts
import {
  AfterContentInit,
  Component,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewChild,
} from '@angular/core';
import { createMarvin, Marvin } from '@chemaxon/marvin';
import { getDefaultSettings } from '@chemaxon/marvin/marvin-extensions';

@Component({
  selector: 'app-marvin',
  standalone: true,
  templateUrl: './marvin.component.html',
  styleUrls: ['./marvin.component.scss'],
})
export class MarvinComponent implements AfterContentInit {
  @Input() settings: any = {};
  @Output() setMarvinRef = new EventEmitter<Marvin>();
  @ViewChild('marvinContainer', { static: true })
  marvinContainer!: ElementRef<HTMLDivElement>;

  ngAfterContentInit() {
    // Set the host for Marvin Web Services for custom / separate backend
    // Example: const MARVIN_WEBSERVICES_HOST = "http://localhost:8080";
    const MARVIN_WEBSERVICES_HOST = '';

    if (this.marvinContainer) {
      createMarvin(this.marvinContainer.nativeElement, {
        ...getDefaultSettings(MARVIN_WEBSERVICES_HOST),
        ...this.settings,
      })
        .then((marvin) => {
          this.setMarvinRef.emit(marvin);
        })
        .catch((error) => {
          console.error('Error initializing Marvin:', error);
        });
    }
  }
}

<div #marvinContainer id="marvin-app"></div>
