// marvin-react/src/components/examples/Examples.tsx
import { useCallback, useState } from "react";
import DocumentExport from "./DocumentExport";
import DocumentImport from "./DocumentImport";
import ImageExport from "./ImageExport";
import "./examples.scss";
import { Marvin } from "@chemaxon/marvin";

type ExampleProps = {
  marvinRef: Marvin | undefined;
};

const Examples = ({ marvinRef }: ExampleProps) => {
  const examples = [
    {
      displayValue: "Document export",
      value: "documentExport",
      component: <DocumentExport marvinRef={marvinRef} />,
    },
    {
      displayValue: "Document import",
      value: "documentImport",
      component: <DocumentImport marvinRef={marvinRef} />,
    },
    {
      displayValue: "Image export",
      value: "imageExport",
      component: <ImageExport marvinRef={marvinRef} />,
    },
  ];

  const [example, setExample] = useState<string>(examples[0].value);

  const renderExample = useCallback(
    () => examples.find((e) => e.value === example)?.component,
    [example, examples]
  );

  return (
    <section id="examples">
      <div className="input-group">
        <label htmlFor="filter-example">Example:</label>
        <select
          onChange={(e) => setExample(e.target.value)}
          name="filter-example"
          id="filter-example"
        >
          {examples.map((e, index) => (
            <option key={index} value={`${e.value}`}>
              {e.displayValue}
            </option>
          ))}
        </select>
      </div>
      {renderExample()}
    </section>
  );
};

export default Examples;

// marvin-vue/src/views/examples/Examples.vue
<template>
  <section id="examples">
    <div class="input-group">
      <label for="filter-example">Example:</label>
      <select v-model="selectedExample" id="filter-example">
        <option v-for="(example, index) in examples" :key="index" :value="example.value">
          {{ example.displayValue }}
        </option>
      </select>
    </div>
    <component :is="currentComponent" :marvin-ref="marvinRef"></component>
  </section>
</template>

<script lang="ts">
import type { PropType } from 'vue'
import DocumentExport from './DocumentExport.vue'
import DocumentImport from './DocumentImport.vue'
import ImageExport from './ImageExport.vue'
import type { Marvin as MarvinRef } from '@chemaxon/marvin'

export default {
  props: {
    marvinRef: {
      type: Object as PropType<MarvinRef | null>,
      required: false
    }
  },
  data() {
    return {
      selectedExample: 'documentExport',
      examples: [
        {
          displayValue: 'Document export',
          value: 'documentExport',
          component: 'DocumentExport'
        },
        {
          displayValue: 'Document import',
          value: 'documentImport',
          component: 'DocumentImport'
        },
        {
          displayValue: 'Image export',
          value: 'imageExport',
          component: 'ImageExport'
        }
      ]
    }
  },
  computed: {
    currentComponent() {
      const example = this.examples.find((e) => e.value === this.selectedExample)
      return example ? example.component : null
    }
  },
  components: {
    DocumentExport,
    DocumentImport,
    ImageExport
  }
}
</script>

<style>
@import './examples.scss';
</style>
