// marvin-angular/src/app/examples/image-export/image-export.component.ts
import {
  Component,
  Input,
  ViewChild,
  ElementRef,
  WritableSignal,
  signal,
} from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { Marvin, ExportOptions, ImageType } from '@chemaxon/marvin';
import { NgIf, NgFor, JsonPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-image-export',
  standalone: true,
  imports: [NgIf, NgFor, FormsModule, JsonPipe],
  templateUrl: './image-export.component.html',
  styleUrls: ['../examples.component.scss'],
})
export class ImageExportComponent {
  @Input() marvinRef?: Marvin;
  @ViewChild('downloadLink') downloadLink!: ElementRef<HTMLAnchorElement>;

  constructor(private sanitizer: DomSanitizer) {}

  imageFormats: ImageType[] = ['SVG', 'PNG', 'JPG', 'WEBP', 'TIFF'];
  format: WritableSignal<ImageType> = signal(this.imageFormats[0]);
  exportOptions: WritableSignal<ExportOptions | null> = signal(null);
  result: WritableSignal<string> = signal('');
  image: WritableSignal<string | undefined> = signal(undefined);
  sanitizedSvg: WritableSignal<SafeHtml | null> = signal(null); // For safe SVG rendering
  width: WritableSignal<number> = signal(230);
  height: WritableSignal<number> = signal(230);

  async exportImage(): Promise<void> {
    if (!this.marvinRef) return;

    const options: ExportOptions = {
      width: this.width(),
      height: this.height(),
    };
    this.exportOptions.set(options);

    const exportedImage = await this.marvinRef.exportImage(
      this.format(),
      options
    );
    if (exportedImage) {
      this.image.set(exportedImage.content);
      this.result.set(exportedImage.content ?? '');

      if (this.format() === 'SVG') {
        this.sanitizedSvg.set(
          this.sanitizer.bypassSecurityTrustHtml(exportedImage.content)
        );
      } else {
        this.sanitizedSvg.set(null);
      }
    }
  }

  async downloadImage(): Promise<void> {
    if (!this.marvinRef || !this.downloadLink) return;

    const options: ExportOptions = {
      width: this.width(),
      height: this.height(),
    };
    const exportedImage = await this.marvinRef.exportImage(
      this.format(),
      options
    );
    this.result.set(exportedImage?.content ?? '');

    const link = this.downloadLink.nativeElement;
    link.href =
      this.format() === 'SVG'
        ? 'data:image/svg+xml;charset=utf-8,' +
          encodeURIComponent(this.result())
        : this.result();
    link.download = `fileName.${this.format().toLowerCase()}`;
    link.click();
  }

  updateFormat(selectedFormat: ImageType): void {
    this.format.set(selectedFormat);
  }

  updateWidth(event: Event): void {
    const value = Number((event.target as HTMLInputElement).value);
    if (!isNaN(value)) this.width.set(value);
  }

  updateHeight(event: Event): void {
    const value = Number((event.target as HTMLInputElement).value);
    if (!isNaN(value)) this.height.set(value);
  }
}

<div class="container-col">
  <div class="btn-group">
    <button (click)="exportImage()" class="btn-export-img">Create image</button>
    <button (click)="downloadImage()" class="btn-download-img">
      Download image
    </button>
  </div>

  <div class="container-row">
    <label for="export-format">Format:</label>
    <select
      [ngModel]="format()"
      (ngModelChange)="updateFormat($event)"
      id="export-image-format"
    >
      <option *ngFor="let f of imageFormats" [value]="f">{{ f }}</option>
    </select>

    <label for="input-width">Width:</label>
    <input
      class="shrinkable-input"
      id="input-width"
      type="text"
      [value]="width()"
      (input)="updateWidth($event)"
    />

    <label for="input-height">Height:</label>
    <input
      class="shrinkable-input"
      id="input-height"
      type="text"
      [value]="height()"
      (input)="updateHeight($event)"
    />
  </div>

  <label for="config-json-image">ImageConfig object:</label>
  <div id="config-json-image">
    <pre *ngIf="exportOptions()">{{ exportOptions() | json }}</pre>
  </div>

  <label>Exported image:</label>
  <div id="image-render">
    <div *ngIf="format() === 'SVG'" [innerHTML]="sanitizedSvg()"></div>
    <img
      *ngIf="format() !== 'SVG' && image()"
      [src]="image()"
      alt="Exported image"
    />
  </div>

  <a class="hidden" id="link-download" #downloadLink></a>
</div>

// marvin-vue/src/views/examples/ImageExport.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import type { ExportOptions, ImageType, Marvin } from '@chemaxon/marvin'

type ExportProps = {
  marvinRef?: Marvin
}

const props = defineProps<ExportProps>()

const imageFormats: ImageType[] = ['SVG', 'PNG', 'JPG', 'WEBP', 'TIFF']

const format = ref<ImageType>(imageFormats[0])
const exportOptions = ref<ExportOptions>()
const result = ref<string>('')
const image = ref<string>('')
const width = ref<number>(0)
const height = ref<number>(0)
const linkRef = ref<HTMLAnchorElement | null>(null)

const exportImage = async () => {
  exportOptions.value = { width: width.value, height: height.value }

  const exportedImage = await props.marvinRef?.exportImage(format.value, exportOptions.value)
  if (exportedImage) image.value = exportedImage.content.toString()

  result.value = exportedImage?.content ?? ''
}

const downloadImage = async () => {
  const options: ExportOptions = { width: width.value, height: height.value }
  const exportedImage = await props.marvinRef?.exportImage(format.value, options)
  result.value = exportedImage?.content ?? ''

  if (linkRef.value) {
    linkRef.value.href =
      format.value === 'SVG'
        ? 'data:text/plain;charset=utf-8,' + encodeURIComponent(result.value)
        : result.value
    linkRef.value.download = `fileName.${format.value.toLowerCase()}`
    linkRef.value.click()
  }
}

const renderImage = computed(() => {
  return format.value === 'SVG'
    ? `<pre>${image.value}</pre>`
    : `<img src="${image.value}" alt="Exported image" />`
})
</script>

<template>
  <div class="container-col">
    <div class="btn-group">
      <button @click="exportImage" class="btn-export-img">Create image</button>
      <button @click="downloadImage" class="btn-download-img">Download image</button>
    </div>

    <div class="container-row">
      <label for="export-format">Format:</label>
      <select v-model="format" id="export-image-format">
        <option v-for="f in imageFormats" :key="f" :value="f">
          {{ f }}
        </option>
      </select>

      <label for="input-width">Width:</label>
      <input class="shrinkable-input" id="input-width" type="text" v-model.number="width" />

      <label for="input-height">Height:</label>
      <input class="shrinkable-input" id="input-height" type="text" v-model.number="height" />
    </div>

    <label for="config-json-image">ImageConfig object:</label>
    <div id="config-json-image">
      <pre v-if="exportOptions">{{ JSON.stringify(exportOptions, null, 2) }}</pre>
    </div>

    <label>Exported image:</label>
    <div id="image-render" v-html="renderImage"></div>

    <a ref="linkRef" class="hidden" id="link-download" href="" download></a>
  </div>
</template>
