// marvin-vue/src/views/examples/Examples.vue
<template>
  <section id="examples">
    <div class="input-group">
      <label for="filter-example">Example:</label>
      <select v-model="selectedExample" id="filter-example">
        <option v-for="(example, index) in examples" :key="index" :value="example.value">
          {{ example.displayValue }}
        </option>
      </select>
    </div>
    <component :is="currentComponent" :marvin-ref="marvinRef"></component>
  </section>
</template>

<script lang="ts">
import type { PropType } from 'vue'
import DocumentExport from './DocumentExport.vue'
import DocumentImport from './DocumentImport.vue'
import ImageExport from './ImageExport.vue'
import type { Marvin as MarvinRef } from '@chemaxon/marvin'

export default {
  props: {
    marvinRef: {
      type: Object as PropType<MarvinRef | null>,
      required: false
    }
  },
  data() {
    return {
      selectedExample: 'documentExport',
      examples: [
        {
          displayValue: 'Document export',
          value: 'documentExport',
          component: 'DocumentExport'
        },
        {
          displayValue: 'Document import',
          value: 'documentImport',
          component: 'DocumentImport'
        },
        {
          displayValue: 'Image export',
          value: 'imageExport',
          component: 'ImageExport'
        }
      ]
    }
  },
  computed: {
    currentComponent() {
      const example = this.examples.find((e) => e.value === this.selectedExample)
      return example ? example.component : null
    }
  },
  components: {
    DocumentExport,
    DocumentImport,
    ImageExport
  }
}
</script>

<style>
@import './examples.scss';
</style>

// marvin-angular/src/app/examples/examples.component.ts
import { Component, Input } from '@angular/core';
import { Marvin } from '@chemaxon/marvin';
import { NgIf, NgFor } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ImageExportComponent } from './image-export/image-export.component';
import { DocumentExportComponent } from './document-export/document-export.component';
import { DocumentImportComponent } from './document-import/document-import.component';

@Component({
  selector: 'app-examples',
  standalone: true,
  imports: [
    NgIf,
    NgFor,
    FormsModule,
    DocumentExportComponent,
    DocumentImportComponent,
    ImageExportComponent,
  ],
  templateUrl: './examples.component.html',
  styleUrls: ['./examples.component.scss'],
})
export class ExamplesComponent {
  @Input() marvinRef?: Marvin;

  selectedExample = 'documentExport';

  examples = [
    { displayValue: 'Document export', value: 'documentExport' },
    { displayValue: 'Document import', value: 'documentImport' },
    { displayValue: 'Image export', value: 'imageExport' },
  ];
}

<section id="examples">
  <div class="input-group">
    <label for="filter-example">Example:</label>
    <select [(ngModel)]="selectedExample" id="filter-example">
      <option *ngFor="let e of examples" [value]="e.value">
        {{ e.displayValue }}
      </option>
    </select>
  </div>

  <app-document-export
    *ngIf="selectedExample === 'documentExport'"
    [marvinRef]="marvinRef"
  ></app-document-export>
  <app-document-import
    *ngIf="selectedExample === 'documentImport'"
    [marvinRef]="marvinRef"
  ></app-document-import>
  <app-image-export
    *ngIf="selectedExample === 'imageExport'"
    [marvinRef]="marvinRef"
  ></app-image-export>
</section>
