// marvin-angular/src/app/examples/document-import/document-import.component.ts
import {
  Component,
  Input,
  signal,
} from '@angular/core';
import { Marvin, ImportOptions } from '@chemaxon/marvin';
import { NgFor } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { PlacementType, ScaleType } from '@chemaxon/marvin/typings/api/marvin';

interface PlacementProps {
  value: PlacementType;
  displayValue: string;
}

interface ScaleProps {
  value: ScaleType;
  displayValue: string;
}

@Component({
  selector: 'app-document-import',
  standalone: true,
  imports: [NgFor, FormsModule],
  templateUrl: './document-import.component.html',
  styleUrls: ['../examples.component.scss'],
})
export class DocumentImportComponent {
  @Input() marvinRef?: Marvin;

  importPlacements: PlacementProps[] = [
    { value: 'CENTER', displayValue: 'Center' },
    { value: 'TOP_LEFT', displayValue: 'Top left corner' },
    { value: 'TOP', displayValue: 'Top' },
    { value: 'TOP_RIGHT', displayValue: 'Top right corner' },
    { value: 'RIGHT', displayValue: 'Right' },
    { value: 'BOTTOM_RIGHT', displayValue: 'Bottom right corner' },
    { value: 'BOTTOM', displayValue: 'Bottom' },
    { value: 'BOTTOM_LEFT', displayValue: 'Bottom left corner' },
    { value: 'LEFT', displayValue: 'Left' },
  ];

  importScales: ScaleProps[] = [
    { value: 'SHRINK', displayValue: 'Shrink large input to screen size' },
    { value: 'NONE', displayValue: 'None' },
  ];

  private _placement = signal<PlacementType>(this.importPlacements[0].value);
  private _scale = signal<ScaleType>(this.importScales[0].value);
  private _documentSource = signal<string>('oxytocin');
  private _isCheckedClear = signal<boolean>(true);
  private _isCheckedSelect = signal<boolean>(true);

  get placement(): PlacementType {
    return this._placement();
  }
  set placement(value: PlacementType) {
    this._placement.set(value);
  }

  get scale(): ScaleType {
    return this._scale();
  }
  set scale(value: ScaleType) {
    this._scale.set(value);
  }

  get documentSource(): string {
    return this._documentSource();
  }
  set documentSource(value: string) {
    this._documentSource.set(value);
  }

  get isCheckedClear(): boolean {
    return this._isCheckedClear();
  }
  set isCheckedClear(value: boolean) {
    this._isCheckedClear.set(value);
  }

  get isCheckedSelect(): boolean {
    return this._isCheckedSelect();
  }
  set isCheckedSelect(value: boolean) {
    this._isCheckedSelect.set(value);
  }

  async importDocument(): Promise<void> {
    if (!this.marvinRef) return;

    const options: ImportOptions = {
      clearCanvas: this.isCheckedClear,
      select: this.isCheckedSelect,
      scale: this.scale,
      placement: this.placement,
      throwError: true,
    };

    await this.marvinRef.importDocument(this.documentSource, options);
  }
}

<div class="import-container">
  <button (click)="importDocument()" class="btn-import">Import</button>

  <div class="import-settings">
    <h3>Import Parameters</h3>

    <!-- Clear Canvas & Select Imported Content -->
    <div class="input-group">
      <label for="check-clear">
        <input id="check-clear" type="checkbox" [(ngModel)]="isCheckedClear" />
        Clear canvas
      </label>

      <label for="check-select">
        <input
          id="check-select"
          type="checkbox"
          [(ngModel)]="isCheckedSelect"
        />
        Select imported content
      </label>
    </div>

    <!-- Scaling Selection -->
    <div class="input-group">
      <label for="select-scaling">Scaling:</label>
      <select id="select-scaling" [(ngModel)]="scale">
        <option *ngFor="let s of importScales" [value]="s.value">
          {{ s.displayValue }}
        </option>
      </select>
    </div>

    <!-- Placement Selection -->
    <div class="input-group">
      <label for="select-placement">Placement:</label>
      <select id="select-placement" [(ngModel)]="placement">
        <option *ngFor="let p of importPlacements" [value]="p.value">
          {{ p.displayValue }}
        </option>
      </select>
    </div>

    <!-- Document Source Input -->
    <div class="textarea-group">
      <label for="config-json-import" class="label-above"
        >Document source:</label
      >
      <textarea
        id="config-json-import"
        class="input-src"
        [(ngModel)]="documentSource"
      ></textarea>
    </div>
  </div>
</div>

// marvin-react/src/components/examples/DocumentImport.tsx
import { Marvin } from "@chemaxon/marvin";
import {
  ImportOptions,
  PlacementType,
  ScaleType,
} from "@chemaxon/marvin/typings/api/marvin";
import { useState } from "react";

type ImportProps = {
  marvinRef?: Marvin;
};

type PlacementProps = {
  value: PlacementType;
  displayValue: string;
};

type ScaleProps = {
  value: ScaleType;
  displayValue: string;
};

const DocumentImport = ({ marvinRef }: ImportProps) => {
  const importPlacements: PlacementProps[] = [
    { value: "CENTER", displayValue: "Center" },
    { value: "TOP_LEFT", displayValue: "Top left corner" },
    { value: "TOP", displayValue: "Top" },
    { value: "TOP_RIGHT", displayValue: "Top right corner" },
    { value: "RIGHT", displayValue: "Right" },
    { value: "BOTTOM_RIGHT", displayValue: "Bottom right corner" },
    { value: "BOTTOM", displayValue: "Bottom" },
    { value: "BOTTOM_LEFT", displayValue: "Bottom left corner" },
    { value: "LEFT", displayValue: "Left" },
  ];

  const importScales: ScaleProps[] = [
    { value: "SHRINK", displayValue: "Shrink large input to screen size" },
    { value: "NONE", displayValue: "None" },
  ];

  const [placement, setPlacement] = useState<PlacementType>(
    importPlacements[0].value
  );
  const [scale, setScale] = useState<ScaleType>(importScales[0].value);
  const [documentSource, setDocumentSource] = useState<string>("oxytocin");
  const [isCheckedClear, setIsCheckedClear] = useState<boolean>(true);
  const [isCheckedSelect, setIsCheckedSelect] = useState<boolean>(true);

  const importDocument = async (): Promise<void> => {
    const options: ImportOptions = {
      clearCanvas: isCheckedClear,
      select: isCheckedSelect,
      scale,
      placement,
      throwError: true,
    };
    await marvinRef?.importDocument(documentSource, options);
  };

  return (
    <div>
      <button onClick={importDocument} className="btn-import">
        Import
      </button>
      <div>
        <label htmlFor="select-format">Parameters:</label>
        <div className="input-group">
          <label htmlFor="check-clear">Clear canvas:</label>
          <input
            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
              setIsCheckedClear(e.target.checked)
            }
            id="check-clear"
            type="checkbox"
            checked={isCheckedClear}
          />
          <label htmlFor="check-select">Select imported content:</label>
          <input
            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
              setIsCheckedSelect(e.target.checked)
            }
            id="check-select"
            type="checkbox"
            checked={isCheckedSelect}
          />
        </div>
        <div className="input-group">
          <label htmlFor="select-scaling">Scaling:</label>
          <select
            onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
              setScale(e.target.value as ScaleType)
            }
            name="scaling"
            id="select-scaling"
          >
            {importScales.map((s, index) => (
              <option key={index} value={`${s.value}`}>
                {s.displayValue}
              </option>
            ))}
          </select>
        </div>
        <div className="input-group">
          <label htmlFor="select-placement">Placement:</label>
          <select
            onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
              setPlacement(e.target.value as PlacementType)
            }
            name="placement"
            id="select-placement"
          >
            {importPlacements.map((p, index) => (
              <option key={index} value={`${p.value}`}>
                {p.displayValue}
              </option>
            ))}
          </select>
        </div>
        <div className="textarea-group">
          <label htmlFor="config-json-import" className="label-above">
            Document source:
          </label>
          <textarea
            onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
              setDocumentSource(e.target.value)
            }
            id="config-json-import"
            className="input-src"
            value={documentSource}
          ></textarea>
        </div>
      </div>
    </div>
  );
};

export default DocumentImport;
