// marvin-vue/src/views/examples/DocumentImport.vue
<template>
  <div>
    <button @click="importDocument" class="btn-import">Import</button>
    <div>
      <label for="select-format">Parameters:</label>
      <div class="input-group">
        <label for="check-clear">Clear canvas:</label>
        <input id="check-clear" type="checkbox" v-model="isCheckedClear" />
        <label for="check-select">Select imported content:</label>
        <input id="check-select" type="checkbox" v-model="isCheckedSelect" />
      </div>
      <div class="input-group">
        <label for="select-scaling">Scaling:</label>
        <select id="select-scaling" v-model="scale">
          <option v-for="(s, index) in importScales" :key="index" :value="s.value">
            {{ s.displayValue }}
          </option>
        </select>
      </div>
      <div class="input-group">
        <label for="select-placement">Placement:</label>
        <select id="select-placement" v-model="placement">
          <option v-for="(p, index) in importPlacements" :key="index" :value="p.value">
            {{ p.displayValue }}
          </option>
        </select>
      </div>
      <div class="textarea-group">
        <label for="config-json-import" class="label-above"> Document source: </label>
        <textarea id="config-json-import" class="input-src" v-model="documentSource"></textarea>
      </div>
    </div>
  </div>
</template>

<script lang="ts">

export default {
  props: {
    marvinRef: {
      type: Object,
      required: false
    }
  },
  data() {
    return {
      importPlacements: [
        { value: 'CENTER', displayValue: 'Center' },
        { value: 'TOP_LEFT', displayValue: 'Top left corner' },
        { value: 'TOP', displayValue: 'Top' },
        { value: 'TOP_RIGHT', displayValue: 'Top right corner' },
        { value: 'RIGHT', displayValue: 'Right' },
        { value: 'BOTTOM_RIGHT', displayValue: 'Bottom right corner' },
        { value: 'BOTTOM', displayValue: 'Bottom' },
        { value: 'BOTTOM_LEFT', displayValue: 'Bottom left corner' },
        { value: 'LEFT', displayValue: 'Left' }
      ],
      importScales: [
        { value: 'SHRINK', displayValue: 'Shrink large input to screen size' },
        { value: 'NONE', displayValue: 'None' }
      ],
      placement: 'CENTER',
      scale: 'SHRINK',
      documentSource: 'oxytocin',
      isCheckedClear: true,
      isCheckedSelect: true
    }
  },
  methods: {
    async importDocument() {
      const options = {
        clearCanvas: this.isCheckedClear,
        select: this.isCheckedSelect,
        scale: this.scale,
        placement: this.placement,
        throwError: true
      }

      try {
        await this.marvinRef?.importDocument(this.documentSource, options)
      } catch (error) {
        console.error('Error importing document:', error)
      }
    }
  }
}
</script>

// marvin-react/src/components/examples/DocumentImport.tsx
import {
  Marvin,
  ImportOptions,
  PlacementType,
  ScaleType,
} from "@chemaxon/marvin";
import { useState } from "react";

type ImportProps = {
  marvinRef?: Marvin;
};

type PlacementProps = {
  value: PlacementType;
  displayValue: string;
};

type ScaleProps = {
  value: ScaleType;
  displayValue: string;
};

const DocumentImport = ({ marvinRef }: ImportProps) => {
  const importPlacements: PlacementProps[] = [
    { value: "CENTER", displayValue: "Center" },
    { value: "TOP_LEFT", displayValue: "Top left corner" },
    { value: "TOP", displayValue: "Top" },
    { value: "TOP_RIGHT", displayValue: "Top right corner" },
    { value: "RIGHT", displayValue: "Right" },
    { value: "BOTTOM_RIGHT", displayValue: "Bottom right corner" },
    { value: "BOTTOM", displayValue: "Bottom" },
    { value: "BOTTOM_LEFT", displayValue: "Bottom left corner" },
    { value: "LEFT", displayValue: "Left" },
  ];

  const importScales: ScaleProps[] = [
    { value: "SHRINK", displayValue: "Shrink large input to screen size" },
    { value: "NONE", displayValue: "None" },
  ];

  const [placement, setPlacement] = useState<PlacementType>(
    importPlacements[0].value
  );
  const [scale, setScale] = useState<ScaleType>(importScales[0].value);
  const [documentSource, setDocumentSource] = useState<string>("oxytocin");
  const [isCheckedClear, setIsCheckedClear] = useState<boolean>(true);
  const [isCheckedSelect, setIsCheckedSelect] = useState<boolean>(true);

  const importDocument = async (): Promise<void> => {
    const options: ImportOptions = {
      clearCanvas: isCheckedClear,
      select: isCheckedSelect,
      scale,
      placement,
      throwError: true,
    };
    await marvinRef?.importDocument(documentSource, options);
  };

  return (
    <div>
      <button onClick={importDocument} className="btn-import">
        Import
      </button>
      <div>
        <label htmlFor="select-format">Parameters:</label>
        <div className="input-group">
          <label htmlFor="check-clear">Clear canvas:</label>
          <input
            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
              setIsCheckedClear(e.target.checked)
            }
            id="check-clear"
            type="checkbox"
            checked={isCheckedClear}
          />
          <label htmlFor="check-select">Select imported content:</label>
          <input
            onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
              setIsCheckedSelect(e.target.checked)
            }
            id="check-select"
            type="checkbox"
            checked={isCheckedSelect}
          />
        </div>
        <div className="input-group">
          <label htmlFor="select-scaling">Scaling:</label>
          <select
            onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
              setScale(e.target.value as ScaleType)
            }
            name="scaling"
            id="select-scaling"
          >
            {importScales.map((s, index) => (
              <option key={index} value={`${s.value}`}>
                {s.displayValue}
              </option>
            ))}
          </select>
        </div>
        <div className="input-group">
          <label htmlFor="select-placement">Placement:</label>
          <select
            onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
              setPlacement(e.target.value as PlacementType)
            }
            name="placement"
            id="select-placement"
          >
            {importPlacements.map((p, index) => (
              <option key={index} value={`${p.value}`}>
                {p.displayValue}
              </option>
            ))}
          </select>
        </div>
        <div className="textarea-group">
          <label htmlFor="config-json-import" className="label-above">
            Document source:
          </label>
          <textarea
            onChange={(e: React.ChangeEvent<HTMLTextAreaElement>) =>
              setDocumentSource(e.target.value)
            }
            id="config-json-import"
            className="input-src"
            value={documentSource}
          ></textarea>
        </div>
      </div>
    </div>
  );
};

export default DocumentImport;
