// marvin-vue/src/views/examples/ImageExport.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import type { ExportOptions, ImageType, Marvin } from '@chemaxon/marvin'

type ExportProps = {
  marvinRef?: Marvin
}

const props = defineProps<ExportProps>()

const imageFormats: ImageType[] = ['SVG', 'PNG', 'JPG', 'WEBP', 'TIFF']

const format = ref<ImageType>(imageFormats[0])
const exportOptions = ref<ExportOptions>()
const result = ref<string>('')
const image = ref<string>('')
const width = ref<number>(0)
const height = ref<number>(0)
const linkRef = ref<HTMLAnchorElement | null>(null)

const exportImage = async () => {
  exportOptions.value = { width: width.value, height: height.value }

  const exportedImage = await props.marvinRef?.exportImage(format.value, exportOptions.value)
  if (exportedImage) image.value = exportedImage.content.toString()

  result.value = exportedImage?.content ?? ''
}

const downloadImage = async () => {
  const options: ExportOptions = { width: width.value, height: height.value }
  const exportedImage = await props.marvinRef?.exportImage(format.value, options)
  result.value = exportedImage?.content ?? ''

  if (linkRef.value) {
    linkRef.value.href =
      format.value === 'SVG'
        ? 'data:text/plain;charset=utf-8,' + encodeURIComponent(result.value)
        : result.value
    linkRef.value.download = `fileName.${format.value.toLowerCase()}`
    linkRef.value.click()
  }
}

const renderImage = computed(() => {
  return format.value === 'SVG'
    ? `<pre>${image.value}</pre>`
    : `<img src="${image.value}" alt="Exported image" />`
})
</script>

<template>
  <div class="container-col">
    <div class="btn-group">
      <button @click="exportImage" class="btn-export-img">Create image</button>
      <button @click="downloadImage" class="btn-download-img">Download image</button>
    </div>

    <div class="container-row">
      <label for="export-format">Format:</label>
      <select v-model="format" id="export-image-format">
        <option v-for="f in imageFormats" :key="f" :value="f">
          {{ f }}
        </option>
      </select>

      <label for="input-width">Width:</label>
      <input class="shrinkable-input" id="input-width" type="text" v-model.number="width" />

      <label for="input-height">Height:</label>
      <input class="shrinkable-input" id="input-height" type="text" v-model.number="height" />
    </div>

    <label for="config-json-image">ImageConfig object:</label>
    <div id="config-json-image">
      <pre v-if="exportOptions">{{ JSON.stringify(exportOptions, null, 2) }}</pre>
    </div>

    <label>Exported image:</label>
    <div id="image-render" v-html="renderImage"></div>

    <a ref="linkRef" class="hidden" id="link-download" href="" download></a>
  </div>
</template>

// marvin-react/src/components/examples/ImageExport.tsx
import { ExportOptions, ImageType, Marvin } from "@chemaxon/marvin";
import { useMemo, useRef, useState } from "react";

type ExportProps = {
  marvinRef?: Marvin;
};

const ImageExport = ({ marvinRef }: ExportProps) => {
  const imageFormats: ImageType[] = ["SVG", "PNG", "JPG", "WEBP", "TIFF"];

  const [format, setFormat] = useState<ImageType>(imageFormats[0]);
  const [exportOptions, setExportOptions] = useState<ExportOptions>();
  const [result, setResult] = useState<string>("");
  const [image, setImage] = useState<string>();
  const [width, setWidth] = useState<number>(0);
  const [height, setHeight] = useState<number>(0);

  const linkRef = useRef<HTMLAnchorElement>(null);

  const exportImage = async (): Promise<void> => {
    setExportOptions({
      width,
      height,
    });

    const exportedImage = await marvinRef?.exportImage(format, exportOptions);
    if (exportedImage) setImage(exportedImage.content.toString());

    setResult(exportedImage?.content ?? "");
  };

  const downloadImage = async (): Promise<void> => {
    const options: ExportOptions = {
      width,
      height,
    };

    const exportedImage = await marvinRef?.exportImage(format, options);
    setResult(exportedImage?.content ?? "");

    if (linkRef.current) {
      linkRef.current.href =
        format === "SVG"
          ? "data:text/plain;charset=utf-8," + encodeURIComponent(result)
          : result;
      linkRef.current.download = `fileName.${format.toLowerCase()}`;
      linkRef.current.click();
    }
  };

  const renderImage = useMemo(() => {
    return format === "SVG" ? (
      <pre dangerouslySetInnerHTML={{ __html: image ? image : "" }}></pre>
    ) : (
      <img src={image} alt="Exported image" />
    );
  }, [format, result]);

  return (
    <div className="container-col">
      <div className="btn-group">
        <button onClick={exportImage} className="btn-export-img">
          Create image
        </button>
        <button onClick={downloadImage} className="btn-download-img">
          Download image
        </button>
      </div>
      <div className="container-row">
        <label htmlFor="export-format">Format:</label>
        <select
          onChange={(e: React.ChangeEvent<HTMLSelectElement>) =>
            setFormat(e.target.value as ImageType)
          }
          id="export-image-format"
        >
          {imageFormats.map((f) => (
            <option onClick={() => setFormat(f)} value={`${f}`}>
              {f}
            </option>
          ))}
        </select>
        <label htmlFor="input-width">Width:</label>
        <input
          className="shrinkable-input"
          id="input-width"
          type="text"
          value={width}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
            Number.isNaN(Number(e.target.value))
              ? setWidth((prev) => prev)
              : setWidth(Number(e.target.value));
          }}
        />
        <label htmlFor="input-height">Height:</label>
        <input
          className="shrinkable-input"
          id="input-height"
          type="text"
          value={height}
          onChange={(e: React.ChangeEvent<HTMLInputElement>) => {
            Number.isNaN(Number(e.target.value))
              ? setHeight((prev) => prev)
              : setHeight(Number(e.target.value));
          }}
        />
      </div>
      <label htmlFor="config-json-image">ImageConfig object:</label>
      <div id="config-json-image">
        {exportOptions ? JSON.stringify(exportOptions, null, 2) : null}
      </div>
      <label>Exported image:</label>
      <div id="image-render">{renderImage}</div>
      <a
        className="hidden"
        id="link-download"
        href=""
        download
        ref={linkRef}
      ></a>
    </div>
  );
};

export default ImageExport;
